/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

/**
 *
 * @author Jelena
 */
public class PanelWelcome extends javax.swing.JPanel {

    /**
     * Creates new form PanelWelcome
     */
    public PanelWelcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImg = new javax.swing.JLabel();

        lblImg.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        lblImg.setForeground(new java.awt.Color(51, 255, 255));
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/background.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 441, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImg;
    // End of variables declaration//GEN-END:variables
}
