/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import javax.swing.table.TableModel;
import model.OpstiDomenskiObjekat;
import view.forms.OpstaEkranskaForma;

/**
 *
 * @author Jelena
 */
public class PanelAllDataSets extends javax.swing.JPanel implements OpstaEkranskaForma{

    /**
     * Creates new form PanelAllDataSets
     */
    public PanelAllDataSets() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatasets = new javax.swing.JTable();

        tblDatasets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatasets);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatasets;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tblDatasets
     */
    public javax.swing.JTable getTblDatasets() {
        return tblDatasets;
    }

    @Override
    public TableModel vratiModel() {
       return tblDatasets.getModel();
    }

    @Override
    public Object[] vratiPocetneVrednosti() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public int vratiSelektovaniRed() {
        return tblDatasets.getSelectedRow();
    }

    @Override
    public OpstiDomenskiObjekat kreirajObjekat() {
        return odo;
    }

    OpstiDomenskiObjekat odo;

    public OpstiDomenskiObjekat getOdo() {
        return odo;
    }

    public void setOdo(OpstiDomenskiObjekat odo) {
        this.odo = odo;
    }
    
}
