/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels.similarity;

import data.DataSetCollection;
import view.panels.importDSpanel.model.TableModelDataSets;

/**
 *
 * @author Djordje
 */
public class PanelSimilarity extends javax.swing.JPanel {

    /**
     * Creates new form PanelSimilarity
     */
    public PanelSimilarity() {
        initComponents();
        TableModelDataSets tmds = new TableModelDataSets(DataSetCollection.getInstance().getDatasets());
        tblAllDatasets.setModel(tmds);
    }

//    public void setActivePanel(PanelAllDataSets newPanel) {
//        if (panelAllDataSets != null) {
//            this.remove(panelAllDataSets);
//        }
//
//
//        panelAllDataSets = newPanel;
//        panelAllDataSets.setSize(getPnlAllDatasets().getSize());
//        panelAllDataSets.setLocation(getPnlAllDatasets().getLocation());
//        getPnlAllDatasets().add(panelAllDataSets, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 780, 500));
//        //getPnlAllDataSets().add(panelAllDataSets);
//        panelAllDataSets.setVisible(true);
//        validate();
//        repaint();
//    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbSimilarity = new javax.swing.JComboBox();
        btnCalculateSimilarity = new javax.swing.JButton();
        lblSimilarityResult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllDatasets = new javax.swing.JTable();

        jLabel1.setText("Select similarity measurement  : ");

        btnCalculateSimilarity.setText("Calculate similarity");

        tblAllDatasets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAllDatasets.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tblAllDatasets);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSimilarityResult, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSimilarity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCalculateSimilarity))
                        .addGap(0, 248, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cbSimilarity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnCalculateSimilarity)
                .addGap(18, 18, 18)
                .addComponent(lblSimilarityResult, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateSimilarity;
    private javax.swing.JComboBox cbSimilarity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSimilarityResult;
    private javax.swing.JTable tblAllDatasets;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cbSimilarity
     */
    public javax.swing.JComboBox getCbSimilarity() {
        return cbSimilarity;
    }

    /**
     * @return the lblSimilarityResult
     */
    public javax.swing.JLabel getLblSimilarityResult() {
        return lblSimilarityResult;
    }
    
    private void addCBItems() {
        
        cbSimilarity.add(this);
    }

}
